---
- hosts: all
  become: true
  tasks:
    # Packages
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - git-svn
        - subversion
        - ruby
        - default-jre

    - gem:
        name: svn2git
        state: latest
        user_install: false
